### PR TITLE
Include the new Allied Races as well as Demon Hunter

### PR DESCRIPTION
**Pull request by chrisb92**

### CODE REVIEW

**Comment by robinescore** [comment]
Cool :)

**Comment by bpfz** [comment]
cool, thanks

**Comment by chrisb92** [comment]
You're welcome! Does anything need to be done for NuGet to update? I'm not familiar with that process.

**Comment by bpfz** [comment]
If you mean install new versions of included nuget packages this needs to be done manually (as changes made could be breaking).

If you mean restoring the packages it should be automatic, and if not it can be done  with the nuget restore command.

**Pull request merged**
